project:
  type: book
  output-dir: _book
  
execute: 
  echo: false
  warning: false

book:
  title: "Cyber Expertise Diversity: RISCS Report"
  author: 
  - name: Matt Spencer
    orcid: 0000-0002-5146-6201
    affiliation: University of Warwick
    affiliation-url: http://warwick.ac.uk/cim
  - name: Carlos Cámara-Menoyo
    orcid: 0000-0002-9378-0549
    affiliations:
    - name: University of Warwick
  - name: Timothy Monteath
    orcid: 0000-0003-2481-9785
    affiliations:
    - name: University of Warwick
  date: "7/18/2025"
  twitter-card: true
  downloads: [pdf, epub]
  output-file: "cyber-expertise-diversiry-report"
  
  repo-url: https://github.com/WarwickCIM/cyberexpertisediversity_survey
  repo-actions: [edit, issue]
  
  chapters:
    - index.qmd
    - content/introduction.qmd
    - content/survey.qmd
#    - part: "Analysis"
#      chapters:
    - content/professionalisation.qmd
    - content/diversity.qmd
    - content/interdisciplinarity.qmd
    - content/conclusions.qmd
    - content/references.qmd
  #appendices:
  #  - content/personal_combs.qmd
  #  - content/scenario_combs.qmd
  
  page-footer: 
    # left: "[![](media/CIM_logo_white.png){height=120}](https://warwick.ac.uk/fac/cross_fac/cim/) [![](media/cropped-RISCS-Banner-Reg1-1.png){height=120}](https://riscs.org.uk/)"
    left:
      - text: "![](/media/CIM_logo_white.png){width=300}"
        href: https://warwick.ac.uk/cim
      # - text: "![](media/cropped-RISCS-Banner-Reg1-1.png){width=400}"
      #   href: https://riscs.org
    right: 
      - icon: mastodon 
        href: https://fediscience.org/%40cimethods
      - icon: twitter
        href: https://bsky.app/profile/cimethods.bsky.social
      - icon: github
        href: https://github.com/WarwickCIM/


bibliography: references.bib



format:
  html:
    theme:
      - cosmo
      - brand
      - css/warwick.scss
    reference-location: margin
  epub: default
  pdf:
    documentclass: book
    pdf-engine: lualatex
    papersize: a4
    # geometry: margin=2.5cm
    fig-width: 6   # custom default figure width (in inches)
    fig-height: 8   # custom default figure height (in inches)
    cover-image: https://riscs.blogs.bristol.ac.uk/files/2024/06/RISCS_scribe_001-1.jpg  # Custom cover for PDF
    aside-to-body: true         # Move asides to body

editor: visual

