---
title: "Professionalisation and exclusion "
format: html
---

## Diversity, equity and the morality of professions

### Social closure

Professionalisation can be analysed sociologically through the lens of social openness and social closure. The concept of social relationships being 'open' or 'closed' has deep roots in sociology, and is a building block of Max Weber's classic analysis of social action [@weber2019economy]. Social closure is an umbrella term for the ways in which groups construct and maintain monopolies over opportunities, by including some people and excluding others. Understanding how and why closure occurs is key to our understanding of social structure and power. It can operate at multiple levels. Even where opportunities are formally open, groups may nevertheless be able to maintain control over resources through influencing access to jobs or status through cronyism or nepotism. Closure can create durable barriers to entry or 'glass ceilings'. The durability of closure arises because, once they exist, monopolies on resources tend to create alignments of interests among group members, a common interest in maintaining the status quo and resisting change. Weber considered guilds to be an 'archetype' of closure where it is motivated by a cooperative monopolisation of (resource) acquisition, and the sociology of professions has studied professionalisation as an important example of social closure in the modern age, as 'occupational closure'.

There is an obvious tension between occupational closure, and the moral projects of social liberalism that promote fair access and equality of opportunity. In the cases of the professions, the justification of occupational closure tends to stress a balance between competing moral principles: on the one hand, for buildings to be safe, for accounts to be trustworthy, for all to have fair and equal representation under the law and for healthcare to be safe, it is necessary to restrict who can practice engineering, accountancy, law and medicine to those who have met a certain standard of qualification and committed to standards of conduct. On the other hand, while entry into these professions may be formally open and non-discriminatory, entrants often need considerable capital—social capital in the form of social networks giving access to opportunities for apprenticeships and experience, cultural capital in the form of the ability to 'fit in,' be 'taken seriously' and generally navigate within professional communities, and financial capital in the form of resources to support what are often extended periods of training or low pay at the start of careers—and so the institutional structure of the professions tends to reinforce existing social inequalities. It is not by accident that the traditional British middle classes are commonly referred to as 'the professional class'. Professional bodies, such as the British Medical Associations, the Law Society, the Association of Chartered Certified Accountants, and so on, thus tend to understand their mission as having two sides: one that focuses on ensuring standards of conduct and competence are met, and the other intervening to support equity of access to the profession, through special initiatives, financial support, community engagement, communication campaigns, and supporting research. In short, professional bodies' interest in equality, diversity and inclusion should not be seen as a separate side project, but as a necessary project that ensures the social legitimacy of occupational closure, by showing that the profession is a vehicle for, and not an obstacle to, fair access.

### The value of diversity

Diversity covers many attributes (race, class, gender, sexuality, religion and disability, for instance). More generally, the term is analysed in terms of variety. Sociologists have argued that organisational or institutional diversity has value as a resource during times of economic transition [@grabher1997organizing]. Scholars in safety studies have argued that overly homogeneous patterns of reasoning and valuation can 'incubate disaster', a central problem for organisations that operate in safety critical contexts [@dekker2014drifting; @vaughan1996challenger]. In Karl Weick's classic studies of high reliability organisations, diversity can be understood as a source of 'requisite variety' that enables organisations to avoid accidents.

> Whether team members differ in occupational specialities, past experience, gender, conceptual skills, or personality may be less crucial than the fact that they do differ and look for different things when they size up a problem. If people look for different things, when their observations are pooled they collectively see more than any one of them alone would see. However, as team members become more alike, their pooled observations cannot be distinguished from their individual observations, which means collectively they know little more about a problem than they know individually.[@weick1987organizational]

Several studies have indicated that hiring people from diverse backgrounds provides value in broadening organisational repertoires of thought and practice, and enhancing the potential to innovate [@herring2009does]. Researchers have also argued that homogeneity can be a source of problems, with evidence, for instance, that homogeneity leads to bubbles and inefficient markets [@levine2014ethnic]. The 2020-2021 NCSC/KPMG Decrypting Diversity reports can thus be understood to build on this tradition of scholarship, arguing that diversity in the workplace brings "benefits including better financial performance, increased creativity and innovation, greater employee satisfaction, lower absenteeism and stronger talent retention" [@NCSC2020decrypting]. The fundamental argument here is that diversity is valuable not just because discrimination is wrong, but also because it is a driver of innovation.

### The status quo

The 'Decrypting Diversity' reports painted a mixed picture of diversity in the cyber security profession. On the one hand, the proportion of the cyber profession that identifies as coming from a BAME (Black and Minority Ethnic) background, and the proportion that identifies as Lesbian, Gay and Bisexual (LGB), were broadly in line with national figures. Data on trans people was insufficient to make reliable claims. Gender is well-recognised to be an issue for cyber security, with survey respondents identifying as male outnumbering those identifying as female 2:1. This, however, is a much broader issue, across many parts of the technology workforce. Socio-economic backgrounds were also skewed, for instance with those who had attended private schools over-represented. Furthermore, even in areas such as ethnicity or sexuality, where the profession was broadly in line with the general population, survey respondents noted that people from BAME backgrounds or who identified as LGB were more likely to have faced discrimination in the workplace.

The Decrypting Diversity report focuses on the experiences of people within the cyber security profession, and although it was intended to be part of a series of studies, only two were carried out.

**What is known about diversity of expertise in cyber??**

## Data analysis

### looking at diversity in general

### looking at individual alignment with the specialisms

### looking at how well people from different backgrounds are aligned with the specialisms

::: callout-note
## Questions for Viz

\- NB when we talk about alignment, we are working with the numbers that we used to call ‘version 2’ of the metric. I think Carlos has updated the code so that this is the only version, but I think when you initially looked at it you were using version 1 – so just something to be aware of.

1.  What does individual alignment look like? You already did some visualisations of alignment in different sectors, and so on. One might expect greater alignment for people with greater numbers of years of experience.

2.  How do you show whether and how inequality translates into greater or lesser alignment with the standardised specialisms? One of the recommendations we will make is that the government and/or the cyber security council should monitor diversity and inclusion in more extensive and rigorous fashion. It would be helpful to show the kinds of views of the data that we think they should be looking at in future work. So anything that you think captures the issue of figuring out whether inequalities are being carried through to the profession, or amplified or suppressed, would be great.

3.  Is there any correlation between diversity and alignment with the specialisms? We can be pretty sure, for instance, that women in cyber are less well aligned with the specialisms than men, because there is no security awareness specialism. Our survey is small and may not actually show this (and if it did we wouldn’t have confidence in it). But we could nevertheless show the kind of perspective on the data that the CSC/government ought to be paying attention to. The same goes for other characteristics than gender.
:::

## Recommendations

### Limitations of the research and the importance of monitoring alignment
